### ISSUE TITLE
ValidationReport.HasUnsupportedExtensions not working

### ISSUE THREAD

**Issue by emackey** [vpenades/GltfValidator#1]
Hi, this is an awesome project.

I found a small issue with `ValidationReport.HasUnsupportedExtensions` always being false here:

https://github.com/vpenades/GltfValidator/blob/e607d3179d01e63eae428ecbd818193b0aba97e3/src/GltfValidator/ValidationReport.API.cs#L99

I think that `item.Text` should be changed to `item.Code` to make this field work.

**Comment by vpenades** [comment]
I'll look into it... in fact I've been waiting for a release of khronos gltf-validator itself.... it seems the project has been abandoned?

**Comment by emackey** [comment]
Not abandoned, just very stable now.  We do have a new extension in the works, KHR_materials_anisotropy. Hopefully there will be a new validator release to cover that and update the list of known prefixes.

**Comment by vpenades** [comment]
Just fixed it and updated nuget packages.
