### ISSUE TITLE
NotSupportedException: Supported platforms: net5.0 and net6.0 on Windows

### ISSUE THREAD

**Issue by SashelI** [vpenades/GltfValidator#2]
Hi,

I just downloaded the nuget package, and wanted to use it in unity (it's a C# .NET library so shouldnt be an issue). Thing is, i get this message every time : "NotSupportedException: Supported platforms: net5.0 and net6.0 on Windows".

Unity does support net5.0 and this message seems to be coded in plain ? I don't know what's causing that ..

Do you have any leads ? thanks.

**Comment by SashelI** [comment]
Nevermind, that's just because the dll in the netstandard folder is an obsolete one ^^"

**Comment by vpenades** [comment]
Unity supports Net5 ?? since when??

As far as I know, Unity supported Net4.5 and NetStandard2.1 at best...

**Comment by SashelI** [comment]
Doesn't NetStandard2.1 include partial NET5.0 compatibility ? https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

in any case, I managed to get this package to work in unity ^^
